/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateScheduleDto {
  details: string;

  /**
   * ISO 8601 datetime
   */
  endTime: string;
  entranceFee: number;
  eventNotes?: string;
  fairName: string;
  notice?: string;
  place: string;
  region: string;

  /**
   * ISO 8601 datetime
   */
  startTime: string;
  thumbnail?: string;
  type?: string;
  year: number;
}
