/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateExhibitorDto {
  boothCount: number;
  boothType: 'SPACE_ONLY' | 'SHELL_SCHEME' | 'PREMIUM';
  businessRegNumber?: string;
  companyName: string;
  contact?: string;
  email?: string;
  managerName?: string;
  options?: Array<string>;
  representativeName?: string;
  scheduleId: number;
  totalFee?: number;
}
