/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExhibitorResponseDto {
  adminMemo?: string;
  boothCount: number;
  boothNumber?: string;
  boothType: 'SPACE_ONLY' | 'SHELL_SCHEME' | 'PREMIUM';
  businessRegNumber: string;
  companyName: string;
  contact: string;
  createdAt: string;
  email: string;
  id: number;
  isExposed: boolean;
  managerName: string;
  options: Array<string>;
  representativeName: string;
  scheduleFairName: string;
  scheduleId: number;
  status: 'PENDING' | 'WAITING_PAYMENT' | 'APPROVED' | 'CANCELED';
  totalFee: number;
  updatedAt: string;
}
