/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FaqResponseDto {
  answer: string;
  createdAt: string;
  id: number;
  isExposed: boolean;
  isPinned: boolean;
  question: string;
  updatedAt: string;
}
