/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GalleryResponseDto {
  content: string;
  createdAt: string;
  eventName: string | null;
  id: number;
  imageUrl: string | null;
  isExposed: boolean;
  keywords: Array<string>;
  shootingDate: string | null;
  title: string;
  updatedAt: string;
  videoUrl: string | null;
}
