/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InquiryResponseDto {
  answer: string | null;
  authorName: string;
  content: string;
  createdAt: string;
  id: number;
  isAnswered: boolean;
  isExposed: boolean;
  title: string;
  updatedAt: string;
}
