/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoticeResponseDto {
  content: string;
  createdAt: string;
  fileUrl: string | null;
  id: number;
  imageURL: string | null;
  isExposed: boolean;
  isPinned: boolean;
  title: string;
  updatedAt: string;
}
