/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationResponseDto {
  id: number;
  reservationNo: string;
  name: string;
  contact: string;
  fairName: string;
  marketingConsent: boolean;
  createdAt: string;
  updatedAt: string;
}
