/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScheduleResponseDto {
  createdAt: string;
  details: string;
  endTime: string;
  entranceFee: number;
  eventNotes?: string;
  fairName: string;
  id: number;
  isExposed: boolean;
  notice?: string;
  place: string;
  region: string;
  startTime: string;
  status: 'PENDING' | 'ONGOING' | 'FINISHED' | 'CANCELLED';
  thumbnail?: string;
  type: string;
  updatedAt: string;
  visitorCount: number;
  year: number;
}
