/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateExhibitorDto {
  adminMemo?: string;
  boothCount?: number;
  boothNumber?: string;
  boothType?: 'SPACE_ONLY' | 'SHELL_SCHEME' | 'PREMIUM';
  businessRegNumber?: string;
  companyName?: string;
  contact?: string;
  email?: string;
  isExposed?: boolean;
  managerName?: string;
  options?: Array<string>;
  representativeName?: string;
  status?: 'PENDING' | 'WAITING_PAYMENT' | 'APPROVED' | 'CANCELED';
  totalFee?: number;
}
