/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type GalleryCategory = 'GALLERY' | 'PRESS';

export interface UpdateGalleryDto {
  category?: GalleryCategory;
  content?: string;
  eventName?: string;
  imageUrl?: string;
  keywords?: Array<string>;
  shootingDate?: string;
  title?: string;
  videoUrl?: string;
}
