/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateGalleryDto {
  content?: string;
  eventName?: string;
  imageUrl?: string;
  keywords?: Array<string>;
  shootingDate?: string;
  title?: string;
  videoUrl?: string;
}
