/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageInfoDto } from '../../models/page-info-dto';
import { ScheduleResponseDto } from '../../models/schedule-response-dto';

export interface ScheduleControllerSearch$Params {
  region?: string;
  year?: number;
  status?: 'PENDING' | 'ONGOING' | 'FINISHED' | 'CANCELLED';
  pageNo?: number;
  pageSize?: number;
  query?: string;
}

export function scheduleControllerSearch(http: HttpClient, rootUrl: string, params?: ScheduleControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'items': Array<ScheduleResponseDto>;
'pageInfo': PageInfoDto;
}>> {
  const rb = new RequestBuilder(rootUrl, scheduleControllerSearch.PATH, 'get');
  if (params) {
    rb.query('region', params.region, {});
    rb.query('year', params.year, {});
    rb.query('status', params.status, {});
    rb.query('pageNo', params.pageNo, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'items': Array<ScheduleResponseDto>;
      'pageInfo': PageInfoDto;
      }>;
    })
  );
}

scheduleControllerSearch.PATH = '/api/schedule/search';
