/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateScheduleDto } from '../../models/create-schedule-dto';
import { ScheduleResponseDto } from '../../models/schedule-response-dto';

export interface ScheduleControllerCreate$Params {
      body: CreateScheduleDto
}

export function scheduleControllerCreate(http: HttpClient, rootUrl: string, params: ScheduleControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ScheduleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, scheduleControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ScheduleResponseDto>;
    })
  );
}

scheduleControllerCreate.PATH = '/api/schedule';
