/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScheduleResponseDto } from '../../models/schedule-response-dto';
import { UpdateScheduleDto } from '../../models/update-schedule-dto';

export interface ScheduleControllerUpdate$Params {
  id: number;
      body: UpdateScheduleDto
}

export function scheduleControllerUpdate(http: HttpClient, rootUrl: string, params: ScheduleControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ScheduleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, scheduleControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ScheduleResponseDto>;
    })
  );
}

scheduleControllerUpdate.PATH = '/api/schedule/{id}';
