// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// apps/server/.env로 이동 후, import "dotenv/config";  ← 이 줄 교체 
import dotenv from "dotenv"; // 교체
dotenv.config({path: "apps/server/.env"}); // 추가
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
