/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoticeResponseDto } from '../../models/notice-response-dto';
import { UpdateNoticeDto } from '../../models/update-notice-dto';

export interface NoticeControllerUpdate$Params {
      body: UpdateNoticeDto
}

export function noticeControllerUpdate(http: HttpClient, rootUrl: string, params: NoticeControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<NoticeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, noticeControllerUpdate.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NoticeResponseDto>;
    })
  );
}

noticeControllerUpdate.PATH = '/api/notice/{id}';
