/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoticeResponseDto } from '../../models/notice-response-dto';

export interface NoticeControllerRemove$Params {
  id: number;
}

export function noticeControllerRemove(http: HttpClient, rootUrl: string, params: NoticeControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<NoticeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, noticeControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NoticeResponseDto>;
    })
  );
}

noticeControllerRemove.PATH = '/api/notice/{id}';
