/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoticeResponseDto } from '../../models/notice-response-dto';

export interface NoticeControllerToggleExpose$Params {
}

export function noticeControllerToggleExpose(http: HttpClient, rootUrl: string, params?: NoticeControllerToggleExpose$Params, context?: HttpContext): Observable<StrictHttpResponse<NoticeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, noticeControllerToggleExpose.PATH, 'patch');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NoticeResponseDto>;
    })
  );
}

noticeControllerToggleExpose.PATH = '/api/notice/{id}/expose';
