/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaqResponseDto } from '../../models/faq-response-dto';

export interface FaqControllerRemove$Params {
  id: number;
}

export function faqControllerRemove(http: HttpClient, rootUrl: string, params: FaqControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<FaqResponseDto>> {
  const rb = new RequestBuilder(rootUrl, faqControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FaqResponseDto>;
    })
  );
}

faqControllerRemove.PATH = '/api/faq/{id}';
