/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaqResponseDto } from '../../models/faq-response-dto';
import { PageInfoDto } from '../../models/page-info-dto';

export interface FaqControllerSearch$Params {
  pageNo?: number;
  pageSize?: number;
  query?: string;
}

export function faqControllerSearch(http: HttpClient, rootUrl: string, params?: FaqControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'items': Array<FaqResponseDto>;
'pageInfo': PageInfoDto;
}>> {
  const rb = new RequestBuilder(rootUrl, faqControllerSearch.PATH, 'get');
  if (params) {
    rb.query('pageNo', params.pageNo, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'items': Array<FaqResponseDto>;
      'pageInfo': PageInfoDto;
      }>;
    })
  );
}

faqControllerSearch.PATH = '/api/faq/search';
