/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaqResponseDto } from '../../models/faq-response-dto';
import { UpdateFaqDto } from '../../models/update-faq-dto';

export interface FaqControllerUpdate$Params {
  id: number;
      body: UpdateFaqDto
}

export function faqControllerUpdate(http: HttpClient, rootUrl: string, params: FaqControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<FaqResponseDto>> {
  const rb = new RequestBuilder(rootUrl, faqControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FaqResponseDto>;
    })
  );
}

faqControllerUpdate.PATH = '/api/faq/{id}';
