/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaqResponseDto } from '../../models/faq-response-dto';

export interface FaqControllerTogglePin$Params {
}

export function faqControllerTogglePin(http: HttpClient, rootUrl: string, params?: FaqControllerTogglePin$Params, context?: HttpContext): Observable<StrictHttpResponse<FaqResponseDto>> {
  const rb = new RequestBuilder(rootUrl, faqControllerTogglePin.PATH, 'patch');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FaqResponseDto>;
    })
  );
}

faqControllerTogglePin.PATH = '/api/faq/{id}/pin';
