/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GalleryControllerUploadImage$Params {
}

export function galleryControllerUploadImage(http: HttpClient, rootUrl: string, params?: GalleryControllerUploadImage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'url'?: string;
}>> {
  const rb = new RequestBuilder(rootUrl, galleryControllerUploadImage.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'url'?: string;
      }>;
    })
  );
}

galleryControllerUploadImage.PATH = '/api/gallery/upload/image';
