/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GalleryCategory, GalleryResponseDto } from '../../models/gallery-response-dto';
import { PageInfoDto } from '../../models/page-info-dto';

export interface GalleryControllerSearch$Params {
  pageNo?: number;
  pageSize?: number;
  query?: string;
  category?: GalleryCategory;
  eventName?: string;
}

export function galleryControllerSearch(http: HttpClient, rootUrl: string, params?: GalleryControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'items': Array<GalleryResponseDto>;
'pageInfo': PageInfoDto;
}>> {
  const rb = new RequestBuilder(rootUrl, galleryControllerSearch.PATH, 'get');
  if (params) {
    rb.query('pageNo', params.pageNo, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('query', params.query, {});
    rb.query('category', params.category, {});
    rb.query('eventName', params.eventName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'items': Array<GalleryResponseDto>;
      'pageInfo': PageInfoDto;
      }>;
    })
  );
}

galleryControllerSearch.PATH = '/api/gallery/search';
