/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GalleryControllerGetEventNames$Params {
}

export function galleryControllerGetEventNames(http: HttpClient, rootUrl: string, params?: GalleryControllerGetEventNames$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'eventNames'?: Array<string>;
}>> {
  const rb = new RequestBuilder(rootUrl, galleryControllerGetEventNames.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'eventNames'?: Array<string>;
      }>;
    })
  );
}

galleryControllerGetEventNames.PATH = '/api/gallery/event-names';
