/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnswerInquiryDto } from '../../models/answer-inquiry-dto';
import { InquiryResponseDto } from '../../models/inquiry-response-dto';

export interface InquiryControllerAnswer$Params {
      body: AnswerInquiryDto
}

export function inquiryControllerAnswer(http: HttpClient, rootUrl: string, params: InquiryControllerAnswer$Params, context?: HttpContext): Observable<StrictHttpResponse<InquiryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, inquiryControllerAnswer.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InquiryResponseDto>;
    })
  );
}

inquiryControllerAnswer.PATH = '/api/inquiry/{id}/answer';
