/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InquiryResponseDto } from '../../models/inquiry-response-dto';

export interface InquiryControllerRemove$Params {
}

export function inquiryControllerRemove(http: HttpClient, rootUrl: string, params?: InquiryControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<InquiryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, inquiryControllerRemove.PATH, 'delete');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InquiryResponseDto>;
    })
  );
}

inquiryControllerRemove.PATH = '/api/inquiry/{id}';
