/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExhibitorResponseDto } from '../../models/exhibitor-response-dto';
import { UpdateExhibitorDto } from '../../models/update-exhibitor-dto';

export interface ExhibitorControllerUpdate$Params {
  id: number;
      body: UpdateExhibitorDto
}

export function exhibitorControllerUpdate(http: HttpClient, rootUrl: string, params: ExhibitorControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ExhibitorResponseDto>> {
  const rb = new RequestBuilder(rootUrl, exhibitorControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExhibitorResponseDto>;
    })
  );
}

exhibitorControllerUpdate.PATH = '/api/exhibitor/{id}';
