/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExhibitorResponseDto } from '../../models/exhibitor-response-dto';

export interface ExhibitorControllerFindOne$Params {
  id: number;
}

export function exhibitorControllerFindOne(http: HttpClient, rootUrl: string, params: ExhibitorControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ExhibitorResponseDto>> {
  const rb = new RequestBuilder(rootUrl, exhibitorControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExhibitorResponseDto>;
    })
  );
}

exhibitorControllerFindOne.PATH = '/api/exhibitor/{id}';
