/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateExhibitorDto } from '../../models/create-exhibitor-dto';
import { ExhibitorResponseDto } from '../../models/exhibitor-response-dto';

export interface ExhibitorControllerCreate$Params {
      body: CreateExhibitorDto
}

export function exhibitorControllerCreate(http: HttpClient, rootUrl: string, params: ExhibitorControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ExhibitorResponseDto>> {
  const rb = new RequestBuilder(rootUrl, exhibitorControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExhibitorResponseDto>;
    })
  );
}

exhibitorControllerCreate.PATH = '/api/exhibitor';
