/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistrationResponseDto } from '../../models/registration-response-dto';

export interface RegistrationControllerRemove$Params {
  id: number;
}

export function registrationControllerRemove(http: HttpClient, rootUrl: string, params: RegistrationControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<RegistrationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, registrationControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegistrationResponseDto>;
    })
  );
}

registrationControllerRemove.PATH = '/api/registration/{id}';
