/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistrationResponseDto } from '../../models/registration-response-dto';

export interface RegistrationControllerCreate$Params {
  body: {
    name: string;
    contact: string;
    fairName: string;
    marketingConsent?: boolean;
  };
}

export function registrationControllerCreate(http: HttpClient, rootUrl: string, params: RegistrationControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<RegistrationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, registrationControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => r as StrictHttpResponse<RegistrationResponseDto>)
  );
}

registrationControllerCreate.PATH = '/api/registration';
