/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistrationResponseDto } from '../../models/registration-response-dto';
import { PageInfoDto } from '../../models/page-info-dto';

export interface RegistrationControllerSearch$Params {
  pageNo?: number;
  pageSize?: number;
  query?: string;
  fairName?: string;
}

export function registrationControllerSearch(http: HttpClient, rootUrl: string, params?: RegistrationControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<{
  'items': Array<RegistrationResponseDto>;
  'pageInfo': PageInfoDto;
}>> {
  const rb = new RequestBuilder(rootUrl, registrationControllerSearch.PATH, 'get');
  if (params) {
    rb.query('pageNo', params.pageNo, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('query', params.query, {});
    rb.query('fairName', params.fairName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
        'items': Array<RegistrationResponseDto>;
        'pageInfo': PageInfoDto;
      }>;
    })
  );
}

registrationControllerSearch.PATH = '/api/registration/search';
